import type {
  ActivityItem,
  Lead,
  LeadSourcePerformance,
  Metric,
  OwnerPerformance,
  PipelineStage,
  Recommendation,
  TaskItem,
} from './leads-types'

export const metrics: Metric[] = [
  { label: 'Total leads', value: '1,248', delta: '+ 15.8% vs May 4 – May 11', icon: 'users', sparkline: [24, 28, 26, 31, 29, 34, 32, 33, 36, 35, 39, 37] },
  { label: 'New this week', value: '156', delta: '+ 22.4% vs May 4 – May 11', icon: 'calendar', sparkline: [10, 16, 20, 18, 15, 16, 17, 18, 19, 21, 23, 28] },
  { label: 'Qualified leads', value: '248', delta: '+ 18.3% vs May 4 – May 11', icon: 'diamond', sparkline: [16, 19, 21, 20, 18, 17, 20, 22, 21, 23, 20, 26] },
  { label: 'High-intent leads', value: '42', delta: '+ 31.5% vs May 4 – May 11', icon: 'users', sparkline: [7, 8, 11, 10, 14, 13, 12, 16, 15, 17, 14, 19] },
  { label: 'Meetings booked', value: '32', delta: '+ 33.3% vs May 4 – May 11', icon: 'calendar', sparkline: [4, 7, 5, 8, 7, 9, 8, 11, 10, 13, 11, 14] },
  { label: 'Avg response rate', value: '26%', delta: '+ 8.7% vs May 4 – May 11', icon: 'trend', sparkline: [19, 21, 20, 23, 22, 24, 23, 26, 25, 27, 26, 29] },
  { label: 'Pipeline value', value: '$1.82M', delta: '+ 15.7% vs May 4 – May 11', icon: 'dollar', sparkline: [36, 37, 38, 39, 38, 40, 42, 43, 44, 45, 47, 49] },
  { label: 'Revenue influenced', value: '$128K', delta: '+ 31.6% vs May 4 – May 11', icon: 'sparkle', sparkline: [11, 13, 12, 16, 15, 17, 14, 18, 17, 20, 19, 23] },
]

export const processSteps = [
  'Capture lead',
  'Qualify',
  'Personalise outreach',
  'Send video',
  'Handle objections',
  'Book call',
  'Close',
]

export const pipelineStages: PipelineStage[] = [
  { label: 'New', count: 32, percentage: 13, color: '#2f6bff' },
  { label: 'Contacted', count: 56, percentage: 23, color: '#19a9ff' },
  { label: 'Qualified', count: 64, percentage: 26, color: '#10d184' },
  { label: 'Proposal Sent', count: 38, percentage: 15, color: '#8c5cff' },
  { label: 'Negotiation', count: 42, percentage: 17, color: '#ff9b2f' },
  { label: 'Won', count: 16, percentage: 6, color: '#f6c445' },
]

export const sourcePerformance: LeadSourcePerformance[] = [
  { source: 'Website', leads: 72, conversion: '28%', value: '$512K', bar: 88, color: '#2f6bff' },
  { source: 'Referral', leads: 48, conversion: '31%', value: '$430K', bar: 74, color: '#17d7c1' },
  { source: 'Cold outreach', leads: 36, conversion: '19%', value: '$216K', bar: 46, color: '#8c5cff' },
  { source: 'Ads', leads: 28, conversion: '22%', value: '$198K', bar: 39, color: '#ff9b2f' },
  { source: 'Organic', leads: 22, conversion: '27%', value: '$164K', bar: 34, color: '#22c55e' },
]

export const ownerPerformance: OwnerPerformance[] = [
  { owner: 'Sarah M.', leads: 72, response: '28%', meetings: 18, revenue: '$512K', avatar: 'SM' },
  { owner: 'James T.', leads: 56, response: '25%', meetings: 14, revenue: '$380K', avatar: 'JT' },
  { owner: 'Emily R.', leads: 48, response: '24%', meetings: 12, revenue: '$310K', avatar: 'ER' },
  { owner: 'Daniel K.', leads: 36, response: '22%', meetings: 8, revenue: '$220K', avatar: 'DK' },
  { owner: 'Michael B.', leads: 28, response: '21%', meetings: 6, revenue: '$150K', avatar: 'MB' },
]

export const leads: Lead[] = [
  {
    id: 'lead-acme',
    contactName: 'Sarah Johnson',
    role: 'Chief Marketing Officer',
    company: 'Acme Corp.',
    companyMark: 'ACME',
    logoClass: 'logoAcme',
    score: 92,
    stage: 'Qualified',
    owner: 'Sarah M.',
    source: 'Website',
    sourceIcon: 'globe',
    lastActivity: '2h ago',
    engagement: 85,
    value: '$120K',
    nextAction: 'Send follow-up',
    selected: true,
  },
  {
    id: 'lead-greentech',
    contactName: 'Mike Chen',
    role: 'VP Sales',
    company: 'GreenTech Solutions',
    companyMark: 'GT',
    logoClass: 'logoGreen',
    score: 88,
    stage: 'Contacted',
    owner: 'James T.',
    source: 'Referral',
    sourceIcon: 'users',
    lastActivity: '4h ago',
    engagement: 80,
    value: '$95K',
    nextAction: 'Book meeting',
  },
  {
    id: 'lead-beta',
    contactName: 'Priya Patel',
    role: 'Head of Operations',
    company: 'Beta Industries',
    companyMark: 'B',
    logoClass: 'logoBeta',
    score: 76,
    stage: 'Proposal Sent',
    owner: 'Emily R.',
    source: 'Cold outreach',
    sourceIcon: 'mail',
    lastActivity: '6h ago',
    engagement: 65,
    value: '$75K',
    nextAction: 'Create proposal',
  },
  {
    id: 'lead-technova',
    contactName: 'Daniel Kim',
    role: 'CTO',
    company: 'TechNova Systems',
    companyMark: 'TN',
    logoClass: 'logoTech',
    score: 72,
    stage: 'Qualified',
    owner: 'Daniel K.',
    source: 'Website',
    sourceIcon: 'globe',
    lastActivity: '1d ago',
    engagement: 60,
    value: '$60K',
    nextAction: 'Nudge reply',
  },
  {
    id: 'lead-brightpath',
    contactName: 'Laura White',
    role: 'Consulting Director',
    company: 'BrightPath Consulting',
    companyMark: 'BP',
    logoClass: 'logoBright',
    score: 68,
    stage: 'New',
    owner: 'Michael B.',
    source: 'Ads',
    sourceIcon: 'sparkle',
    lastActivity: '1d ago',
    engagement: 45,
    value: '$45K',
    nextAction: 'Send follow-up',
  },
  {
    id: 'lead-cloudpeak',
    contactName: 'Tom Richards',
    role: 'IT Manager',
    company: 'CloudPeak Inc.',
    companyMark: 'CP',
    logoClass: 'logoCloud',
    score: 64,
    stage: 'Contacted',
    owner: 'Sarah M.',
    source: 'Organic',
    sourceIcon: 'diamond',
    lastActivity: '2d ago',
    engagement: 40,
    value: '$40K',
    nextAction: 'Book meeting',
  },
  {
    id: 'lead-vertex',
    contactName: 'Alex Nguyen',
    role: 'Data Analyst',
    company: 'Vertex Analytics',
    companyMark: 'VA',
    logoClass: 'logoVertex',
    score: 60,
    stage: 'Negotiation',
    owner: 'James T.',
    source: 'Referral',
    sourceIcon: 'users',
    lastActivity: '2d ago',
    engagement: 70,
    value: '$110K',
    nextAction: 'Schedule call',
  },
]

export const tasks: TaskItem[] = [
  { label: 'Follow up with 5 high-intent leads', time: '10:00 AM', checked: true },
  { label: 'Video presentation for Acme Corp', time: '11:00 AM', checked: true },
  { label: 'Discovery call with Sarah Johnson', time: '1:00 PM', checked: true },
  { label: 'Proposal review with James T.', time: '3:00 PM' },
  { label: 'Send pricing to GreenTech', time: '4:30 PM' },
]

export const recommendations: Recommendation[] = [
  { title: 'Follow up with Acme Corp', detail: 'High engagement +92% in 2 days', action: 'Follow up', icon: 'sparkle', tone: 'purple' },
  { title: 'Create video for GreenTech', detail: 'Viewed 80% of your last video', action: 'Create video', icon: 'video', tone: 'red' },
  { title: 'Nudge reply from Daniel Kim', detail: 'Opened email 2 days ago', action: 'Nudge', icon: 'clock', tone: 'yellow' },
]

export const recentActivity: ActivityItem[] = [
  { title: 'Sarah M. booked a call with Acme Corp', time: 'May 18, 10:15 AM' },
  { title: 'James T. sent a video to GreenTech', time: 'May 18, 9:45 AM' },
  { title: 'Emily R. moved lead to Proposal Sent', time: 'May 18, 8:32 AM' },
  { title: 'Daniel K. logged a call with Beta Industries', time: 'May 17, 6:40 PM' },
  { title: 'Michael B. created a proposal for Vertex', time: 'May 17, 5:20 PM' },
]
